#!/bin/sh
# Git hook template: call the changelog updater automatically after each commit.
# To enable hooks from this directory run:
#   git config core.hooksPath .githooks

MSG=$(git log -1 --pretty=%B)
python3 scripts/update_changelogs.py "$MSG"
