# Generated by Django 5.2.8 on 2025-11-17 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
            ],
            options={
                "verbose_name": "Departman",
                "verbose_name_plural": "Departmanlar",
            },
        ),
        migrations.CreateModel(
            name="Title",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
            ],
            options={
                "verbose_name": "Ünvan",
                "verbose_name_plural": "Ünvanlar",
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gms",
                    models.CharField(blank=True, max_length=100, verbose_name="GMS"),
                ),
                (
                    "phone_fixed",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Sabit Telefon"
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Doğum Tarihi"
                    ),
                ),
                (
                    "tc_no",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="TC Kimlik No"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="Adres")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="accounts/photos/",
                        verbose_name="Vesikalık Resim",
                    ),
                ),
                (
                    "record_date",
                    models.DateField(auto_now_add=True, verbose_name="Kayıt Tarihi"),
                ),
                (
                    "job_start",
                    models.DateField(
                        blank=True, null=True, verbose_name="İş Giriş Tarihi"
                    ),
                ),
                (
                    "job_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="İş Çıkış Tarihi"
                    ),
                ),
                (
                    "is_active_employee",
                    models.BooleanField(
                        default=False,
                        help_text="Aktif kullanıcı sisteme giriş yapabilir.",
                        verbose_name="Kullanım Durumu",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="profiles",
                        to="accounts.department",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "title",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="profiles",
                        to="accounts.title",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kullanıcı Profili",
                "verbose_name_plural": "Kullanıcı Profilleri",
            },
        ),
    ]
