# Generated by Django 5.2.8 on 2025-11-16 21:09

"""Initial database schema for the `proje` app.

This migration defines the core models (Owner, Project, Unit, Agreement,
Document, etc.) required by the application. The docstring is added
for linting/readability and does not affect migration behavior.
"""

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    """Initial migration for `proje` models."""

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Owner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Ad")),
                ("last_name", models.CharField(max_length=100, verbose_name="Soyad")),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Doğum Tarihi"
                    ),
                ),
                (
                    "tc_no",
                    models.CharField(blank=True, max_length=20, verbose_name="TC"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=30, verbose_name="Telefon"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-Posta"
                    ),
                ),
                (
                    "landline",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Sabit Tel"
                    ),
                ),
                (
                    "relative_phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Yakını Tel"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="Adres")),
                (
                    "disabled",
                    models.BooleanField(default=False, verbose_name="Engel Durumu"),
                ),
                (
                    "literate",
                    models.BooleanField(default=True, verbose_name="Okur Yazar"),
                ),
                (
                    "education",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Mezun Okul"
                    ),
                ),
                (
                    "employment",
                    models.CharField(
                        choices=[
                            ("calismiyor", "Çalışmıyor"),
                            ("okuyor", "Okuyor"),
                            ("evhanimi", "Ev Hanımı"),
                            ("calisiyor", "Çalışıyor"),
                            ("diger", "Diğer"),
                        ],
                        default="calisiyor",
                        max_length=30,
                        verbose_name="Çalışma Durumu",
                    ),
                ),
                (
                    "residence_city",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="İkamet İli"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="owners/photos/",
                        verbose_name="Vesikalık Resim",
                    ),
                ),
                (
                    "id_scan",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="owners/id/",
                        verbose_name="Kimlik Fotokopisi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Malik",
                "verbose_name_plural": "Malikler",
            },
        ),
        migrations.CreateModel(
            name="Ownership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "share_percent",
                    models.DecimalField(decimal_places=2, default=100, max_digits=6),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="Satılmış / vefaat / devir gibi durumlar",
                        max_length=30,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="proje.owner"
                    ),
                ),
            ],
            options={
                "verbose_name": "Mülk Sahibi Hissesi",
                "verbose_name_plural": "Mülk Sahibi Hisseleri",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Proje Adı")),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Proje Kodu"
                    ),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=255, verbose_name="Konum"),
                ),
                (
                    "area_m2",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Proje M2",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("kentsel", "Kentsel Dönüşüm"),
                            ("altyapi", "Altyapı"),
                            ("insaat", "İnşaat"),
                        ],
                        default="kentsel",
                        max_length=50,
                        verbose_name="Proje Tipi",
                    ),
                ),
                (
                    "est_delivery_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Tahmini Teslim Tarihi"
                    ),
                ),
                (
                    "est_budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Tahmini Bütçe",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planlama", "Planlama Aşamasında"),
                            ("uzlasma", "Uzlaşma Aşamasında"),
                            ("tamamlandi", "Tamamlandı"),
                            ("hukuk", "Hukuki Süreçte"),
                            ("yikim", "Yıkım Başladı"),
                        ],
                        default="planlama",
                        max_length=32,
                        verbose_name="Proje Durumu",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Başlangıç Tarihi"
                    ),
                ),
                (
                    "est_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Tahmini Bitiş Tarihi"
                    ),
                ),
                (
                    "unit_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Mevcut Bağımsız Bölüm Sayısı"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "staff",
                    models.ManyToManyField(
                        blank=True, related_name="projects", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Proje",
                "verbose_name_plural": "Projeler",
            },
        ),
        migrations.AddField(
            model_name="owner",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owners",
                to="proje.project",
            ),
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ada", models.CharField(blank=True, max_length=50)),
                ("parsel", models.CharField(blank=True, max_length=50)),
                (
                    "m2",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Metrekare",
                    ),
                ),
                ("address", models.TextField(blank=True)),
                (
                    "door_outside",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Dış Kapı No"
                    ),
                ),
                (
                    "door_inside",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="İç Kapı No"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("daire", "Daire"),
                            ("bina", "Bina"),
                            ("dukkan", "Dükkan"),
                            ("arsa", "Arsa"),
                            ("tarla", "Tarla"),
                            ("atil", "Atıl Durumda"),
                            ("diger", "Diğer"),
                        ],
                        default="daire",
                        max_length=20,
                        verbose_name="Tip",
                    ),
                ),
                (
                    "current_m2",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Mevcut M2",
                    ),
                ),
                (
                    "share_m2",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Arsa Payı M2",
                    ),
                ),
                (
                    "occupancy",
                    models.CharField(
                        choices=[
                            ("sahip_oturuyor", "Mülk sahibi oturuyor"),
                            ("kiraci", "Kiracı Mevcut"),
                            ("bos", "Boş"),
                            ("kullanilmiyor", "Kullanılmıyor"),
                        ],
                        default="bos",
                        max_length=30,
                        verbose_name="Oturum Durumu",
                    ),
                ),
                (
                    "agreement_status",
                    models.CharField(
                        choices=[
                            ("beklemede", "Uzlaşma Beklemede"),
                            ("saglandi", "Uzlaşma Sağlandı"),
                            ("istemiyor", "Uzlaşma İstemiyor"),
                            ("ulasilamadi", "Ulaşılamıyor"),
                        ],
                        default="beklemede",
                        max_length=30,
                        verbose_name="Uzlaşma Durumu",
                    ),
                ),
                (
                    "owners",
                    models.ManyToManyField(
                        blank=True,
                        related_name="units",
                        through="proje.Ownership",
                        to="proje.owner",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="proje.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bağımsız Bölüm",
                "verbose_name_plural": "Bağımsız Bölümler",
            },
        ),
        migrations.AddField(
            model_name="ownership",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="proje.unit"
            ),
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="proje_documents/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="proje.project",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="proje.unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proje Dosyası",
                "verbose_name_plural": "Proje Dosyaları",
            },
        ),
        migrations.CreateModel(
            name="Agreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("beklemede", "Uzlaşma Beklemede"),
                            ("saglandi", "Uzlaşma Sağlandı"),
                            ("istemiyor", "Uzlaşma İstemiyor"),
                            ("ulasilamadi", "Ulaşılamıyor"),
                        ],
                        default="beklemede",
                        max_length=30,
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owners",
                    models.ManyToManyField(
                        blank=True, related_name="agreements", to="proje.owner"
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agreements",
                        to="proje.unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Uzlaşma",
                "verbose_name_plural": "Uzlaşmalar",
            },
        ),
    ]
