# Generated by Django 5.2.8 on 2025-11-16 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proje", "0002_create_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="label",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Dosya Adı"
            ),
        ),
    ]
