# Generated by Django 5.2.8 on 2025-11-16 22:17

"""Add a `label` field to `Document` model.

This migration introduces the `label` CharField to store a human-readable
file name for uploaded documents. The module docstring is added for
linting clarity and does not change migration semantics.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proje", "0002_create_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="label",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Dosya Adı"
            ),
        ),
    ]
